---
- name: RPMFusion | Calc repo urls
  ansible.builtin.set_fact:
    _rpmfusion_repos:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    _rpmfusion_keys:
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
  changed_when: false

- name: RPMFusion | Add GPG keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ _rpmfusion_keys }}"

- name: RPMFusion | Add repositories
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ _rpmfusion_repos }}"
