---
- name: Truncate /etc/machine-id
  ansible.builtin.shell:
    cmd: truncate -s 0 /etc/machine-id

- name: Get stat for /var/lib/dbus/machine-id
  ansible.builtin.stat:
    path: /var/lib/dbus/machine-id
    follow: true
  register: _dbus_machine_id
  changed_when:: false

- name: Create symlink from /var/lib/dbus/machine-id to /etc/machine-id
  when: not _dbus_machine_id.stat.exists or (_dbus_machine_id.stat.islnk and _dbus_machine_id.stat.path == '/etc/machine-id')
  ansible.builtin.file:
    src: /var/lib/dbus/machine-id
    dest: /etc/machine-id
    state: link
