---
- name: Create and set permissions for .ssh directory
  become_user: "{{ userid }}"
  file:
    path: "/home/{{ userid }}/.ssh"
    mode: 0700
    state: directory

- name: create authorized_keys file
  become_user: "{{ userid }}"
  file:
    path: "/home/{{ userid }}/.ssh/authorized_keys"
    state: touch
    mode: 0644

- name: Add id to authorized_keys
  become_user: "{{ userid }}"
  vars:
    pub_content: "{{ lookup('file', '/home/{{ userid }}/.ssh/{{ public_key }}') }}"
  lineinfile:
    dest: /home/{{ userid }}/.ssh/authorized_keys
    regexp: "^{{ pub_content }}"
    line: "{{ pub_content }}"
    state: present
