---
- name: Install base packages.
  ansible.builtin.package:
    name: xorg
    state: present

- name: Set video_driver fact
  ansible.builtin.set_fact:
    _xf86_video_driver: "{{ '' if ansible_virtualization_type == 'virtualbox' else x11.video_card_driver }}"
  changed_when: false

- name: Install card driver
  when: _xf86_video_driver|length > 0
  ansible.builtin.package:
    name: "{{ _xf86_video_driver }}"
    state: present

- name: Install window manager.
  ansible.builtin.include_tasks: "window_manager/{{ x11.window_manager }}.yaml"

- name: Install display manager.
  ansible.builtin.include_tasks: "display_manager/{{ x11.display_manager }}.yaml"
