---
- name: Get version to download
  ansible.builtin.set_fact:
    version: "{{ cloud_version[cloud_distribution] }}"

- name: Set Ubuntu cloud image url
  when: cloud_distribution == 'ubuntu'
  ansible.builtin.set_fact:
    _image_url: "https://cloud-images.ubuntu.com/{{ version }}/current/{{ version }}-server-cloudimg-amd64.img"

- name: Set Fedora cloud image url
  when: cloud_distribution == 'fedora'
  ansible.builtin.set_fact:
    _image_url: "https://download.fedoraproject.org/pub/fedora/linux/releases/{{ version }}/Cloud/x86_64/images/Fedora-Cloud-Base-{{ version }}-1.2.x86_64.qcow2"

- name: Set main disk image filename
  ansible.builtin.set_fact:
    disk_image_main: "~/images/{{ cloud_distribution }}-{{ version }}-cloud-init-enabled{{ disk_image_extension }}"

- name: Create target directory
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    path: ~/images/
    state: directory
    mode: 0700
    access_time: preserve
    modification_time: preserve

- name: Download cloud image
  delegate_to: localhost
  become: false
  ansible.builtin.uri:
    url: "{{ _image_url }}"
    dest: "{{ disk_image_main }}"
    mode: 0644
    status_code: [200, 304]
    creates: "{{ disk_image_main }}"

- name: Copy cloud image
  ansible.builtin.copy:
    src: "{{ disk_image_main }}"
    dest: "{{ disk_image_main }}"
    mode: 0600
    access_time: preserve
    modification_time: preserve

#https://access.redhat.com/downloads/content/69/ver=/rhel---7/7.0/x86_64/product-downloads
#https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2
