---
- name: Get installation targets by type
  ansible.builtin.set_fact:
    _overrides: "{{ _install_overrides|_install_types(os_family, distribution) }}"

- name: dbg
  ansible.builtin.debug:
    msg: "{{ _overrides }}"

# - name: Compile items
#   when: _overrides['compile'] is defined and _overrides['compile'] | length > 0
#   include_role:
#     name: package_compile
#   vars:
#     compile_info: "{{ compileinfo }}"
#   loop: "{{ _overrides['compile'] }}"
#   loop_control:
#     loop_var: compileinfo

# - name: Install items using a role
#   when: _overrides['role'] is defined and _overrides['role'] | length > 0
#   include_role:
#     name: "{{ roleinfo.package }}"
#   loop: "{{ _overrides['role'] }}"
#   loop_control:
#     loop_var: roleinfo

# - name: Install os packages
#   ansible.builtin.package:
#     name: "{{ item }}"
#     state: present
#   loop: "{{ package_list }}"
