---
- hosts: ansible_vbox
  become: true
  become_method: sudo
  vars_files:
    - ../vars/main.yaml
    - ../vars/secrets.yaml
    - ./vars/pypi.yaml

  pre_tasks:
    - name: Debug
      ansible.builtin.debug:
        msg:
          - "Computed stats"
          - "  Username: {{ remote_user }}"
          - "  Configuration file home directory: {{ config_home }}"
          - "  Shell: {{ shell }}"
          - "  Distribution: {{ distribution }}"
          - "  OS Family: {{ os_family }}"
          - "  Architecture: {{ ansible_architecture }}"

  tasks:
    - name: Install git
      ansible.builtin.include_role:
        name: git

    - name: Load os package list
      ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - '{{distribution}}.yaml'
            - '{{os_family}}.yaml'
          paths:
            - 'vars'

    - name: Install OS packages
      ansible.builtin.include_role:
        name: os_package
      vars:
        custom_os_packages: "{{ os_packages }}"

    - name: Install Pypi packages
      ansible.builtin.include_role:
        name: pypi_package
      vars:
        custom_pypi_packages: "{{ pypi_packages }}"

    - name: Copy playbooks
      ansible.builtin.git:
        repo: https://github.com/sffjunkie/ansiblefiles
        dest: ~/ansible/
        version: develop

    - name: "Disable pi user"
      ansible.builtin.user:
        name: pi
        expires: 1
        password_lock: true
      when: distribution == 'raspbian'
