# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook
---
- hosts: ansible
  become: true
  vars_files:
    - ../common/vars/global.yaml

  roles:
    - playbook_packages

  tasks:
    - name: Load os/distribution specific package list
      ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - '{{ distribution }}.yaml'
            - '{{ os_family }}.yaml'
          paths:
            - 'vars'

    - name: Install packages required by playbook
      ansible.builtin.include_role:
        name: playbook_packages
      vars:
        group_info: "{{ base }}"

    # - name: Copy playbooks
    #   ansible.builtin.git:
    #     repo: https://github.com/sffjunkie/ansiblefiles
    #     dest: "/home {{ user_id }} /ansible/"
    #     version: develop

    - name: "Disable pi user"
      when: distribution == 'raspbian'
      ansible.builtin.user:
        name: pi
        expires: 1
        password_lock: true
