---
extends: default

ignore: |
  ansible_collections/
  ansible_roles/
  cloud_init/build/
  trash/

rules:
  comments-indentation: disable
  line-length:
    max: 90
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 1
