---
- name: Pyenv | Set pyenv_root fact
  ansible.builtin.set_fact:
    pyenv_root: "$_LOCAL_HOME/pyenv"

- name: Pyenv | Install pyenv
  become_user: "{{ userid }}"
  ansible.builtin.shell: "curl https://pyenv.run | bash"  # noqa command-instead-of-module
  environment:
    PYENV_ROOT: "{{ pyenv_root }}"
  args:
    creates: "{{ pyenv_root }}"

- name: Pyenv | Install pyenv-virtualenv
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ pyenv_root }}/plugins/pyenv-virtualenv"
    version: "{{ pyenv_version }}"

- name: Pyenv | Update configfiles
  block:
    - name: Pyenv | Calc config
      ansible.builtin.set_fact:
        _pyenv_config:
          pyenv:
            PYENV_ROOT: "{{ pyenv_root | replace(home, '${HOME}') }}"
      changed_when: false

    - name: Pyenv | Calc new configfiles fact
      ansible.utils.update_fact:
        updates:
          - path: configfiles.configs
            value: "{{ configfiles.configs | combine(_pyenv_config) }}"
          - path: configfiles.pathstart
            value: >
              "{{ [local_home_replacement_text + '/pyenv/bin']
              + configfiles.pathstart }}"
          - path: configfiles.packages
            value: "{{ configfiles.packages + ['pyenv'] }}"
      register: _updated_fact
      changed_when: false

    - name: Pyenv | Update configfiles fact
      ansible.builtin.set_fact:
        configfiles: "{{ _updated_fact.configfiles }}"
      changed_when: false
