---
- name: Development Environments | Pyenv | Set pyenv_root fact
  ansible.builtin.set_fact:
    pyenv_root: "/home/{{ user_id }}/.local/pyenv"
    pyenv_root_text: "{{ local_home_text }}/pyenv"

- name: Development Environments | Pyenv | Install
  become_user: "{{ user_id }}"
  ansible.builtin.shell:
    cmd: "curl https://pyenv.run | bash"  # noqa command-instead-of-module line-length
    creates: "{{ pyenv_root }}"
  environment:
    PYENV_ROOT: "{{ pyenv_root }}"

- name: Development Environments | Pyenv | Install pyenv-virtualenv
  become_user: "{{ user_id }}"
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ pyenv_root }}/plugins/pyenv-virtualenv"
    version: "{{ pyenv_version }}"

- name: Development Environments | Pyenv | Update output_config
  block:
    - name: Development Environments | Pyenv | Calc config
      ansible.builtin.set_fact:
        _pyenv_config:
          pyenv:
            PYENV_ROOT: "{{ pyenv_root_text }}"
      changed_when: false

    - name: Development Environments | Pyenv | Calc new output_config
      ansible.utils.update_fact:
        updates:
          - path: "output_config.user[{{ user_idx }}].configs"
            value: "{{ output_config.user[user_idx].configs | combine(_pyenv_config) }}"

          - path: "output_config.user[{{ user_idx }}].pathstart"
            value: >
              {{ [local_home_text + '/pyenv/bin']
              + output_config.user[user_idx].pathstart }}

          - path: "output_config.user[{{ user_idx }}].packages"
            value: "{{ output_config.user[user_idx].packages + ['pyenv'] }}"
      register: _updated_fact
      changed_when: false

    - name: Development Environments | Pyenv | Update output_config
      ansible.builtin.set_fact:
        output_config: "{{ _updated_fact.output_config }}"
      changed_when: false
