---
- name: VS Code
  ansible.builtin.debug:
    msg: Building VSCode environment
    verbosity: 1

- name: Install vscode
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"
      # TODO: Can we have a default - "default.yaml"

- name: Calc config directory
  ansible.builtin.set_fact:
    _vscode_config_dir: >
      "{{ (vscode.product | lower == 'vscode') |
      ternary('Code', 'VSCodium') }}"

# Using custom filter plugins
- name: Get VSCode extension list
  ansible.builtin.set_fact:
    _vscode_extensions: "{{ vscode | vscode_extension_install_strings }}"
    _vscode_settings: "{{ vscode | vscode_extension_settings }}"

- name: Install extensions
  become_user: "{{ userid }}"
  ansible.builtin.command:
    cmd: >-
      code --install-extension '{{ item }}'
      --user-data-dir $HOME/Code/User/
    creates: "{{ item }}-*"
  loop: "{{ _vscode_extensions }}"
  register: _vscode_extension_install_result
  changed_when: >
    _vscode_extension_install_result.rc == 0 and
    'already installed' not in _vscode_extension_install_result.stdout

- name: Update configfiles for VS Code
  block:
    - name: Set VS Code information
      ansible.builtin.set_fact:
        _vscode_config:
          vscode:
            settings: "{{ _vscode_settings }}"

    - name: Add vscode info to configfiles
      ansible.utils.update_fact:
        updates:
          - path: configfiles.packages
            value: "{{ configfiles.packages + ['vscode'] }}"
          - path: configfiles.configs
            value: "{{ configfiles.configs | combine(_vscode_config) }}"
      register: _updated_fact
      changed_when: false

    - name: Set configfiles fact
      ansible.builtin.set_fact:
        configfiles: "{{ _updated_fact.configfiles }}"
      changed_when: false
