---
- name: User | System | Create | Ensure user's password is encrypted.
  ansible.builtin.include_tasks: "{{ common_tasks_directory }}/encrypted_password.yaml"

- name: User | System | Create | Add user
  ansible.builtin.user:
    name: "{{ user.id }}"
    password: "{{ user.password }}"
    state: present

- name: User | System | Create | Add sudo rights for user
  when: "user.groups is defined and 'sudo' in user.groups"
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ user.id }}"
    content: "{{ user.id }} {{ user_sudo_entry }}"
    mode: 0644
    validate: "visudo -cf %s"
