---
- name: Avatar | Get avatar extension
  ansible.builtin.set_fact:
    _avatar_ext: "{{ avatar | splitext | last }}"

- name: Avatar | Create folders
  ansible.builtin.file:
    path: "/var/lib/AccountsService/{{ directory }}"
    state: directory
    mode: 0755
    access_time: preserve
    modification_time: preserve
  loop:
    - icons
    - users
  loop_control:
    loop_var: directory

- name: Avatar | Copy
  ansible.builtin.copy:
    src: "{{ avatar }}"
    dest: "/var/lib/AccountsService/icons/{{ user_id }}{{ _avatar_ext }}"
    mode: 0644

- name: Avatar | Create accountsservice config for user
  ansible.builtin.template:
    src: templates/accountsservice.ini
    dest: "/var/lib/AccountsService/users/{{ user_id }}"
    mode: 0644
