---
- name: Include theme info vars
  ansible.builtin.include_vars: ../vars/vscode_theme.yaml

- name: Install vscode
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"
      - "default.yaml"

- name: Install extensions
  ansible.builtin.command:
    cmd: "code --install-extension '{{ item }}'"
  loop: "{{ vscode.extensions.local + vscode.extensions.remote }}"

- name: Configure theme
  block:
    - name: Calc color theme extension
      ansible.builtin.set_fact:
        _vscode_theme_extension: "{{ vscode_themes[color_scheme].extension }}"

    - name: Install theme extension
      ansible.builtin.command:
        cmd: code --install-extension "{{ _vscode_theme_extension }}"
      when: _vscode_theme_extension | length > 0
