---
- name: Build nocloud configs and image
  hosts: localhost
  vars_files:
    - ./vars/main.yaml

  tasks:
    - name: Include secrets.yaml
      ansible.builtin.include_vars:
        file: secrets.yaml
      register: _include_secrets
      failed_when: false

    - name: Assert default_user exists if user.use_default_user is true
      assert:
        that: not user.use_default_user or (user.use_default_user and default_user is defined)

    - ansible.builtin.set_fact:
        _config_name_str: "cloud-config"

    - name: Set config_name
      when: cli_config_name | default('', True) != ''
      ansible.builtin.set_fact:
        _config_name_str: "{{ _config_name_str }}-{{ cli_config_name }}"

    - name: Set config_name
      when: "'config_name' in hostvars[inventory_hostname] and not cli_config_name is defined"
      ansible.builtin.set_fact:
        _config_name_str: "{{ _config_name_str }}-{{ hostvars[inventory_hostname]['config_name'] }}"

    - name: If using date
      when: use_date
      block:
        - name: Get date
          ansible.builtin.command:
            cmd: date +"%Y-%m-%d"
          register: _date
          changed_when: false

        - name: Set date string
          ansible.builtin.set_fact:
            _config_name_str: "{{ _config_name_str }}-{{ _date.stdout }}"

    - name: Calc image name
      ansible.builtin.set_fact:
        image_path: "./build/images/{{ _config_name_str }}.img"

    - ansible.builtin.set_fact:
        user_config_path: ./build/configs/{{ _config_name_str }}-user.yaml
        meta_config_path: ./build/configs/{{ _config_name_str }}-meta.yaml

    - ansible.builtin.include_role:
        name: build_cloud_config
      tags: config

    - ansible.builtin.include_role:
        name: build_cloud_config_image
      tags: image

- name: Copy nocloud image and configs
  hosts: vm_nodes_test  # FIXME: Replace with vm_nodes
  become: true
  vars_files:
    - ./vars/main.yaml
    - ./vars/secrets.yaml
  tags: copy

  tasks:
    - name: Copy images
      ansible.builtin.copy:
        src: "{{ hostvars['localhost']['image_path'] }}"
        dest: ~/images/

    - name: Copy user config
      ansible.builtin.copy:
        src: "{{ hostvars['localhost']['user_config_path'] }}"
        dest: ~/snippets/

    - name: Copy meta config
      ansible.builtin.copy:
        src: "{{ hostvars['localhost']['meta_config_path'] }}"
        dest: ~/snippets/
