---
- name: Calc scheme file name
  ansible.builtin.set_fact:
    _scheme_file: "{{ 'base16-' ~ base16.color_scheme ~ (('-' ~ color_count) if color_count == 256 else '') ~ '.yml' }}"

- name: Get color definitions
  ansible.builtin.set_fact:
    alacritty_colors: "{{ base16_schemes['schemes'][base16.color_scheme]['alacritty']['colors'][_scheme_file] }}"

- name: Make alacritty directory
  ansible.builtin.file:
    name: output/.config/alacritty
    state: directory
    access_time: preserve
    modification_time: preserve

- name: Alacritty
  ansible.builtin.template:
    src: templates/.config/alacritty/alacritty.yml.j2
    dest: output/.config/alacritty/alacritty.yml
    mode: 0700
