---
- name: Firewall | Configure OS firewall
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"
