---
- name: Run install script
  become_user: "{{ userid }}"
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    creates: "{{ _ohmyzsh_install_path }}/oh-my-zsh.sh"
  environment:
    ZSH: "{{ _ohmyzsh_install_path }}"

- name: Install plugins.
  become_user: "{{ userid }}"
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/{{ item }}.git"
    dest: "{{ _ohmyzsh_install_path }}/plugins/{{ item }}"
  loop:
    "{{ machine.ohmyzsh.user_plugins }}"

- name: Update configfiles for oh-my-zsh
  block:
    - ansible.builtin.set_fact:
        _ohmyzsh_config:
          ohmyzsh:
            plugins: "{{ machine.ohmyzsh.plugins + machine.ohmyzsh.user_plugins }}"
            ZSH: "{{ _ohmyzsh_install_path|replace(home, '${HOME}') }}"

    - ansible.utils.update_fact:
        updates:
          - path: configfiles.configs
            value: "{{ configfiles.configs | combine(_ohmyzsh_config) }}"
      register: _updated_fact
      changed_when: false

    - ansible.builtin.set_fact:
        configfiles: "{{ _updated_fact.configfiles }}"
      changed_when: false
