---
- name: Oh-My-Zsh | Run install script
  become_user: "{{ userid }}"
  ansible.builtin.shell:
    cmd: >
      sh -c
      \"$(curl -fsSL
      https://raw.githubusercontent.com\
      /ohmyzsh/ohmyzsh/master/tools/install.sh)\"
      \"\"
      --unattended
    creates: "{{ _ohmyzsh_install_path }}/oh-my-zsh.sh"
  environment:
    ZSH: "{{ _ohmyzsh_install_path }}"

- name: Oh-My-Zsh | Install plugins.
  become_user: "{{ userid }}"
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/{{ item.name }}.git"
    dest: "{{ _ohmyzsh_install_path }}/plugins/{{ item.name }}"
    version: "{{ item.version }}"
  loop:
    "{{ machine.ohmyzsh.zsh_users_plugins }}"

- name: Oh-My-Zsh | Update configfiles
  block:
    - name: Calc user plugin names
      ansible.builtin.set_fact:
        _ohmyzsh_user_plugins: >
          "{{ machine.ohmyzsh.zsh_users_plugins | map(attribut='name') | list }}"

    - name: Oh-My-Zsh | Calc config
      ansible.builtin.set_fact:
        _ohmyzsh_config:
          ohmyzsh:
            plugins: "{{ machine.ohmyzsh.plugins + _ohmyzsh_user_plugins }}"
            ZSH: "{{ _ohmyzsh_install_path|replace(home, '${HOME}') }}"

    - name: Oh-My-Zsh | Calc new configfiles fact
      ansible.utils.update_fact:
        updates:
          - path: configfiles.configs
            value: "{{ configfiles.configs | combine(_ohmyzsh_config) }}"
      register: _updated_fact
      changed_when: false

    - name: Oh-My-Zsh | Update configfiles fact
      ansible.builtin.set_fact:
        configfiles: "{{ _updated_fact.configfiles }}"
      changed_when: false
