---
- name: Include theme info vars
  ansible.builtin.include_vars: "{{ playbook_dir }}/../vars/_vscode-theme.yaml"

- name: Install vscode
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"
      - "default.yaml"

- name: Install extensions
  become_user: "{{ userid }}"
  ansible.builtin.command:
    cmd: "code --install-extension '{{ item }}' --user-data-dir {{ config_home }}/Code/User/"
    creates: "{{ item }}-*"
  loop: "{{ development.vscode.extensions }}"
  register: _vscode_extension
  changed_when: _vscode_extension.rc == 0 and 'already installed' not in _vscode_extension.stdout

# - name: Configure theme
#   block:
#     - name: Calc color theme extension
#       ansible.builtin.set_fact:
#         _vscode_theme_extension: "{{ vscode_themes[color_scheme].extension }}"

#     - name: Install theme extension
#       ansible.builtin.command:
#         cmd: code --install-extension "{{ _vscode_theme_extension }}"
#       when: _vscode_theme_extension | length > 0
