---
# https://github.com/jnsh/arc-theme
- name: Gtk | Theme | Arc | Install Tasks
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"
      - "default.yaml"
