---
- name: Update xdg_user_dirs with custom values
  set_fact:
    xdg_user_dirs: "{{ xdg_user_dirs | default('') | combine({ item.key : item.value }) }}"
  loop: "{{ custom_xdg_user_dirs | dict2items }}"

- name: Create XDG user directories
  when: item.value | default("", True) | length > 0
  ansible.builtin.file:
    path: "/home/{{ username }}/{{ item.value }}"
    state: directory
    mode: 0755
    access_time: preserve
    modification_time: preserve
  loop: "{{ xdg_user_dirs | dict2items }}"

- name: Create user-dirs.dirs files
  ansible.builtin.template:
    src: "templates/user-dirs.dirs"
    dest: "/home/{{ username }}/.config/user-dirs.dirs"
    mode: 0600

- name: Update XDG directories
  ansible.builtin.shell:  # noqa command-instead-of-shell
    cmd: xdg-user-dirs-update
  register: updateresult
  changed_when: updateresult.rc == 0
