---
- name: Install podman
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"
      - "default.yaml"

- name: Start podman socket
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: true
