---
- name: Ensure each item has 'env' and 'version' keys
  set_fact:
    plist: "{{ plist + [dict_defaults | combine(item)] }}"
  loop: "{{ package_list }}"
  when: package_list | length > 0

- name: Pypi package
  pip:
    name: "{{ item.name }}{{ (';' + item.env) | default('', True) }}"
    version: "{{ item.version | default('', True) }}"
    state: present
  loop: "{{ plist  }}"
  when: plist | length > 0
