---
- name: apt updgrade all
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: true
  when: os_family == "debian"

- name: yum updgrade all
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: true
  when: os_family == "centos"

- name: dnf updgrade all
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  when: os_family == "fedora"

- name: pacman update all
  community.general.pacman:
    upgrade: true
  when: os_family == "archlinux"
