# https://docs.docker.com/engine/install/fedora/
---
- name: Install dnf core plugins
  ansible.builtin.package:
    name: dnf-plugins-core

- name: Add docker repository
  ansible.builtin.shell:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
