---
- name: Setup docker repository
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"

- name: Install docker from package manager
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Start docker.socket
  ansible.builtin.systemd:
    name: docker.socket
    state: started
    enabled: true

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
