---
# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    update_cache: true
    name: docker-ce
    state: latest

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker

- name: Install docker-compose
  ansible.builtin.package:
    name: docker-compose
    state: present
