---
- name: Set hostname
  ansible.builtin.shell:
    cmd: hostnamectl set-hostname "{{ hostname }}"

- name: Change /etc/hosts
  when: os_family == 'debian'
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ hostname }}"
    state: present
