---
- name: Encrypted Password | Calc hashed password
  delegate_to: localhost
  when: user.password[0] != '$'
  ansible.builtin.command:
    cmd: mkpasswd --method=SHA-512 --rounds=4096
  register: _passwd
  changed_when: false

- name: Encrypted Password | Get already hashed passwd
  when: user.password[0] != '$'
  ansible.builtin.set_fact:
    user_passwd: "{{ _passwd.stdout }}"
  changed_when: false

- name: Encrypted Password | Set user_passwd fact
  when: user.password[0] == '$'
  ansible.builtin.set_fact:
    user_passwd: "{{ user.password }}"
  changed_when: false
