---
- name: Load common package list
  ansible.builtin.include_vars: vars/common.yaml

- name: Load default base package list
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ distribution }}.yaml"
        - "{{ os_family }}.yaml"
      paths:
        - "vars"
  register: _included_os

- name: Ensure values are lists
  ansible.builtin.set_fact:
    _base_pip: >
      {{ base.pip | default([], True) |
      j2render_list(hostvars[inventory_hostname]) }}

    _base_packages: >
      {{ base.packages | default([], True) |
      j2render_list(hostvars[inventory_hostname]) }}

    _common_pip: >
      {{ common.pip | default([], True) |
      j2render_list(hostvars[inventory_hostname]) }}

    _common_packages: >
      {{ common.packages | default([], True) |
      j2render_list(hostvars[inventory_hostname]) }}

    _extra_pip: >
      {{ extra.pip | default([], True) |
      j2render_list(hostvars[inventory_hostname]) }}

    _extra_packages: >
      {{ extra.packages | default([], True) |
      j2render_list(hostvars[inventory_hostname]) }}

- name: Update list with common and extra packages
  ansible.utils.update_fact:
    updates:
      - path: base.packages
        value: "{{ (_base_packages + _common_packages + _extra_packages) | unique }}"
      - path: base.pip
        value: "{{ (_base_pip + _common_pip + _extra_pip) | unique }}"
  register: _updated_fact
  changed_when: false

- name: Set updated 'base' fact
  ansible.builtin.set_fact:
    base: "{{ _updated_fact.base }}"
  changed_when: false

- name: Install base items
  ansible.builtin.include_role:
    name: install_group
  vars:
    group: "{{ base }}"
