---
- name: Playbook Packages | Load common package list
  ansible.builtin.include_vars: vars/common.yaml

- name: Playbook Packages | Load os/distribution specific package list
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ distribution }}.yaml"
        - "{{ os_family }}.yaml"
      paths:
        - "vars"

# Merge common (common.yaml), base (vars/*.yaml) and extra (passed into role)
- name: Update install_group info
  ansible.builtin.include_tasks: "{{ common_tasks_directory }}/install_group_update.yaml"

- name: Playbook Packages | Install group
  ansible.builtin.include_role:
    name: install_group
  vars:
    group: "{{ group_info }}"
