---
- name: User | SSH | Create and set permissions for .ssh directory
  ansible.builtin.file:
    path: "/home/{{ user.id }}/.ssh"
    mode: 0700
    state: directory
    owner: "{{ user.id }}"
    group: "{{ user.id }}"
    access_time: preserve
    modification_time: preserve

- name: User | SSH | Create authorized_keys file
  ansible.builtin.file:
    path: "/home/{{ user.id }}/.ssh/authorized_keys"
    state: touch
    mode: 0644
    owner: "{{ user.id }}"
    group: "{{ user.id }}"
    access_time: preserve
    modification_time: preserve

- name: User | SSH | Get keyfile content
  become_user: "{{ user.id }}"
  when: user.ssh_public_key_file is defined
  ansible.builtin.set_fact:
    pub_content: >-
      {{ lookup('file', user.ssh_public_key_file | expanduser) }}
  changed_when: false

- name: User | SSH | Get keyfile content
  when: user.ssh_public_key is defined
  ansible.builtin.set_fact:
    pub_content: "{{ user.ssh_public_key }}"
  changed_when: false

- name: User | SSH | Add id to authorized_keys
  vars:
  ansible.builtin.lineinfile:
    dest: /home/{{ user.id }}/.ssh/authorized_keys
    regexp: "^{{ pub_content }}"
    line: "{{ pub_content }}"
    state: present
