---
- name: Create and set permissions for .ssh directory
  ansible.builtin.file:
    path: "/home/{{ userid }}/.ssh"
    mode: 0700
    state: directory
    owner: "{{ userid }}"
    group: "{{ userid }}"
    access_time: preserve
    modification_time: preserve

- name: create authorized_keys file
  ansible.builtin.file:
    path: "/home/{{ userid }}/.ssh/authorized_keys"
    state: touch
    mode: 0644
    owner: "{{ userid }}"
    group: "{{ userid }}"
    access_time: preserve
    modification_time: preserve

- name: Add id to authorized_keys
  become_user: "{{ userid }}"
  vars:
    pub_content: "{{ lookup('file', '/home/{{ userid }}/.ssh/{{ public_key }}') }}"
  ansible.builtin.lineinfile:
    dest: /home/{{ userid }}/.ssh/authorized_keys
    regexp: "^{{ pub_content }}"
    line: "{{ pub_content }}"
    state: present
