---
- name: Install git
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"
      - "default.yaml"

- name: Configure git name
  when: git.name | length > 0
  become_user: "{{ user.id }}"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ user.name }}"
    state: present
  loop: "{{ users }}"
  loop_control: "user"

- name: Configure git email
  when: user.git.email | length > 0
  become_user: "{{ user.id }}"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ user.git.email }}"
    state: present
  loop: "{{ users }}"
  loop_control: "user"

- name: Configure git GPG Key
  when: git.gpg_key | default("", True) | length > 0
  become_user: "{{ user.id }}"
  community.general.git_config:
    name: user.signingKey
    scope: global
    value: "{{ user.git.gpg_key }}"
    state: present
  loop: "{{ users }}"
  loop_control: "user"
