- name: Add Git PPA
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Install git
  ansible.builtin.apt:
    name: git
    state: latest
    update_cache: true
    cache_valid_time: 86400
