- name: Git | Ubuntu | Add PPA
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Git | Ubuntu | Install package
  ansible.builtin.apt:
    name: git
    state: latest
    update_cache: true
    cache_valid_time: 86400
