---
- name: Install zsh
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"
      - "default.yaml"

- name: Update configfiles for ZSH
  ansible.utils.update_fact:
    updates:
      - path: configfiles.configs
        value: "{{ configfiles.configs + 'zsh' }}"
      - path: configfiles.envvars
        value: "{{ configfiles.envvars | combine({'ZDOTDIR': config_home_replacement_text + '/zsh'}) }}"
  register: _updated_fact
  changed_when: false

- name: Set configfiles
  ansible.builtin.set_fact:
    configfiles: "{{ _updated_fact.configfiles }}"
  changed_when: false
