---
- name: Install git - os specific method
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"
      - "default.yaml"

- name: Add zsh to configfiles fact
  ansible.builtin.set_fact:
    configfiles: "{{ configfiles + ['zsh'] }}"
