---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../vars/development.yaml
    - ../vars/_playbook.yaml
    - ./vars/main.yaml

  pre_tasks:
    - name: Import configuration
      ansible.builtin.set_fact:
        configfiles: "{{ lookup('file', playbook_dir + '/../configfiles.json') | from_json }}"

    - name: Display info
      ansible.builtin.debug:
        msg:
          - "Config files: {{ configfiles }}"

  # roles:
  #   - mnussbaum.base16-builder-ansible

  tasks:
    - name: Go config
      ansible.builtin.include_tasks: includes/development/go.yaml
      when: '"go" in configfiles.configs'

  #   - name: Node config
  #     ansible.builtin.include_tasks: includes/development/node.yaml
  #     when: '"node" in config_roles'

  #   - name: Python config
  #     ansible.builtin.include_tasks: includes/development/python.yaml
  #     when: '"python" in config_roles'

  #   - name: Rust config
  #     ansible.builtin.include_tasks: includes/development/rust.yaml
  #     when: '"rust" in config_roles'

  #   - name: Zsh config
  #     ansible.builtin.include_tasks: includes/shell/zsh.yaml
  #     when: '"zsh" in config_roles'

  #   - name: Generate scheme colors
  #     ansible.builtin.base16_builder:
  #       scheme: "{{ base16.color_scheme }}"
  #       template: "{{ base16.templates }}"
  #     register: base16_schemes

  #   # - debug:
  #   #     var: base16_schemes

  #   - name: Alacritty Config
  #     ansible.builtin.include_tasks: includes/application/alacritty.yaml
  #     when: '"alacritty" in applications'

  #   - name: Copy files to output
  #     ansible.builtin.copy:
  #       src: files/*
  #       dest: output/
