---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../vars/development.yaml
    - ../vars/laptop.yaml
    - ../vars/_playbook.yaml
    - ./vars/main.yaml

  pre_tasks:
    - name: Import configuration
      ansible.builtin.set_fact:
        configfiles: "{{ lookup('file', playbook_dir + '/../configfiles.json') | from_json }}"

    - name: Display info
      ansible.builtin.debug:
        msg:
          - "Config files: {{ configfiles }}"

  roles:
    - mnussbaum.base16-builder-ansible

  tasks:
    - name: Go config
      ansible.builtin.include_tasks: includes/development/go.yaml
      when: '"go" in configfiles.configs'

  #   - name: Node config
  #     when: '"node" in config_roles'
  #     ansible.builtin.include_tasks: includes/development/node.yaml

  #   - name: Python config
  #     when: '"python" in config_roles'
  #     ansible.builtin.include_tasks: includes/development/python.yaml

  #   - name: Rust config
  #     when: '"rust" in config_roles'
  #     ansible.builtin.include_tasks: includes/development/rust.yaml

  #   - name: Zsh config
  #     when: '"zsh" in config_roles'
  #     ansible.builtin.include_tasks: includes/shell/zsh.yaml

    - name: Generate scheme colors
      base16_builder:
        scheme: "{{ base16.color_scheme }}"
        template: "{{ base16.templates }}"
      register: base16_schemes

  #   # - debug:
  #   #     var: base16_schemes

    - name: Alacritty Config
      when: '"alacritty" in applications'
      ansible.builtin.include_tasks: includes/application/alacritty.yaml

  #   - name: Copy files to output
  #     ansible.builtin.copy:
  #       src: files/*
  #       dest: output/
