---
- name: Install xmonad dependencies
  ansible.builtin.package:
    name:
      - libx11-dev
      - libxinerama-dev
      - libxext-dev
      - libxrandr-dev
      - libxss-dev
      - libxft-dev
      - libghc-xmonad-dev
      - libghc-xmonad-contrib-dev
    state: present

- name: Install xmonad with stack
  become_user: "{{ userid }}"
  ansible.builtin.command: ~/.local/bin/stack install xmonad
