---
- name: Set pyenv_root fact
  ansible.builtin.set_fact:
    pyenv_root: "{{ local_home }}/pyenv"

- name: Install pyenv
  become_user: "{{ userid }}"
  shell: "curl https://pyenv.run | bash"  # noqa command-instead-of-module
  environment:
    PYENV_ROOT: "{{ pyenv_root }}"
  args:
    creates: "{{ pyenv_root }}"
  changed_when: false

- name: Install pyenv-virtualenv
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ pyenv_root }}/plugins/pyenv-virtualenv"

- name: Update configfiles for pyenv
  block:
    - ansible.builtin.set_fact:
        _pyenv_config:
          pyenv:
            PYENV_ROOT: "{{ pyenv_root | replace(home, '${HOME}') }}"
      changed_when: false

    - ansible.utils.update_fact:
        updates:
          - path: configfiles.configs
            value: "{{ configfiles.configs | combine(_pyenv_config) }}"
          - path: configfiles.pathstart
            value: "{{ [local_home_replacement_text + '/pyenv/bin'] + configfiles.pathstart }}"
      register: _updated_fact
      changed_when: false

    - ansible.builtin.set_fact:
        configfiles: "{{ _updated_fact.configfiles }}"
      changed_when: false
