---
- name: Install Zsh
  block:
    - name: ZSH | Test if installed
      ansible.builtin.command:
        cmd: zsh --version
      register: _zsh_installed
      changed_when: false
      failed_when: false

    - name: ZSH | Already Installed
      when: _zsh_installed.rc == 0
      ansible.builtin.debug:
        msg: "Skipping: ZSH already installed"

    - name: ZSH | Install
      when: _zsh_installed.rc != 0
      ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
      vars:
        subtasks:
          - "{{ distribution }}.yaml"
          - "{{ os_family }}.yaml"
          - "default.yaml"

  # Install when any user has it set
  when: "'zsh' in (config.user | map(attribute='shell'))"
