# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook
---
- hosts: vm_nodes
  become: true
  vars_files:
    - ../common/vars/global.yaml

  roles:
    - configure_apt_sources
    - role: playbook_packages
      extra:
        pip:
          - proxmoxer
          - requests
    - no_valid_subscription
    - darkmode
    - vzdump_config
