---
base_os_packages:
  - accountsservice
  - apt-transport-https
  - build-essential
  - ca-certificates
  - python3
  - python3-apt
  - python3-pip
  - software-properties-common
  - unattended-upgrades
  - unzip
