---
- name: Install LightDM
  ansible.builtin.package:
    name: lightdm
    state: present

- name: Install LightDM GTK Greeter
  ansible.builtin.package:
    name: lightdm-gtk-greeter
    state: present

- name: Enable lightdm
  ansible.builtin.systemd:
    name: lightdm
    enabled: true

- name: Configure LightDM
  ansible.builtin.template:
    src: templates/50-laptop.conf
    dest: /etc/lightdm/lightdm.conf.d/50-laptop.conf
    mode: 0644
