---
- name: Bat | Install
  ansible.builtin.package:
    name: bat
    state: present

- name: Bat | Update aliases
  block:
    - name: Bat | Add alias as the executable is named batcat on debian
      when: os_family == 'debian'
      ansible.builtin.set_fact:
        _bat_aliases: ['cat', 'batcat']

    - name: Bat | If not debian add alias to bat
      when: os_family != 'debian'
      ansible.builtin.set_fact:
        _bat_aliases: ['cat', 'bat']

    - name: Bat | Calc new configfiles fact
      ansible.utils.update_fact:
        updates:
          - path: configfiles.aliases
            value: "{{ configfiles.aliases + [_bat_aliases] }}"
      register: _updated_fact
      changed_when: false

    - name: Bat | Update configfiles fact
      ansible.builtin.set_fact:
        configfiles: "{{ _updated_fact.configfiles }}"
      changed_when: false
