- name: Font Install | Delete temporary files
  ansible.builtin.file:
    name: "{{ _font_tmp_dir }}"
    state: absent

- name: Font Install | Update font cache
  ansible.builtin.command: fc-cache -f -v
