---
- hosts: laptop
  become: true
  vars:
    ansible_port: "{{ ssh_port }}"
  vars_files:
    - ../common/vars/install_overrides.yaml
    - ../common/vars/playbook.yaml

  pre_tasks:
    - name: Debug
      ansible.builtin.debug:
        msg:
          - "Computed stats"
          - "  Shell: {{ shell }}"
          - "  Development Environments: {{ development.roles | join(', ') }}"

    - name: Initial configuration
      ansible.builtin.debug:
        msg: "{{ configfiles }}"

  roles:
    # - dotlocal_directories
    # - git
    # - base_os_packages
    - development

    - role: install_packages
      install: "{{ apps }}"

    # - x11
    # - avatar
    # - docker
    # - exa
    # - fonts

    # - role: zsh
    #   when: shell == 'zsh'
    #   set_shell_for: "{{ userid }}"

    # - role: ohmyzsh
    #   when: shell == 'zsh' and ohmyzsh is defined

  tasks:
    - name: Final configuration
      ansible.builtin.debug:
        msg: "{{ configfiles }}"

    - name: Store final configuration
      delegate_to: localhost
      ansible.builtin.copy:
        dest: "{{ playbook_dir }}/../configfiles.json"
        content: "{{ configfiles | to_nice_json }}"
      changed_when: false

# - name: Run configfiles playbook
#   ansible.builtin.import_playbook: ../configfiles/build.yaml
#   tags:
#     - configfiles

  # - name: Run scriptfiles playbook
  #   ansible.builtin.import_playbook: ../scriptfiles/main.yaml
  #   tags:
  #     - scriptfiles

  # - name: Copy config files
  #   ansible.builtin.copy:
  #     src: "{{ configfiles_path }}/*"
  #     dest: "/home/{{ user.id }}/"
