---
- hosts: laptop
  become: true
  vars:
    ansible_port: "{{ ssh_port }}"
  vars_files:
    - ../common/vars/install_overrides.yaml
    - ../common/vars/playbook.yaml

  roles:
    # - base_packages
    # - git
    # - docker
    # - dotlocal_directories

    # Install development environments before applications so we have
    # compilers avaiable to build the applications if needed.
    # - dev_environments

    - role: install_packages
      install: "{{ machine.apps }}"

    # - x11
    # - avatar
    # - fonts
# - role: arc_theme

    # - role: zsh
    #   when: machine.shell == 'zsh'
    #   set_shell_for: "{{ userid }}"

    # - role: ohmyzsh
    #   when: machine.shell == 'zsh' and machine.ohmyzsh is defined

  tasks:
    - name: Sort packages
      ansible.utils.update_fact:
        updates:
          - path: configfiles.packages
            value: "{{ configfiles.packages | sort }}"
      register: _updated_fact
      changed_when: false

    - name: Update configfiles
      ansible.builtin.set_fact:
        configfiles: "{{ _updated_fact.configfiles }}"
      changed_when: false

    - name: Add machine vars to configfiles
      block:
        - ansible.utils.update_fact:
            updates:
              - path: configfiles.machine
                value: "{{ machine }}"
          register: _updated_fact
          changed_when: false

        - name: Set configfiles fact
          ansible.builtin.set_fact:
            configfiles: "{{ _updated_fact.configfiles }}"
          changed_when: false

    # - name: Final configuration
    #   ansible.builtin.debug:
    #     msg: "{{ configfiles }}"

    - name: Store final configuration
      delegate_to: localhost
      ansible.builtin.copy:
        dest: "{{ playbook_dir }}/../configfiles.json"
        content: "{{ configfiles | to_nice_json }}"
      changed_when: false

# - name: Run configfiles playbook
#   ansible.builtin.import_playbook: ../configfiles/build.yaml
#   tags:
#     - configfiles

  # - name: Run scriptfiles playbook
  #   ansible.builtin.import_playbook: ../scriptfiles/main.yaml
  #   tags:
  #     - scriptfiles

  # - name: Copy config files
  #   ansible.builtin.copy:
  #     src: "{{ configfiles_path }}/*"
  #     dest: "/home/{{ user.id }}/"
