---
- hosts: laptops
  become: true
  vars_files:
    - ./vars/install_overrides.yaml
    - ../common/vars/global.yaml

  pre_tasks:
    - name: Build info
      ansible.builtin.debug:
        msg: "Ansible User: {{ ansible_user }}"

  roles:
    - output_config_user_list
    - playbook_repositories
    - playbook_packages
      extra:
        package:
          - sfdisk
    # - os_packages
    # - git
    # - zsh
    # - pipewire
    # - dev_common
    # - user_per_user

    # - x11
    # - system_fonts

  tasks:
    - name: Sort packages
      ansible.utils.update_fact:
        updates:
          - path: output_config.system.packages
            value: "{{ output_config.system.packages | sort }}"
      register: _updated_fact
      changed_when: false

    - name: Update output_config for system
      ansible.builtin.set_fact:
        output_config: "{{ _updated_fact.output_config }}"
      changed_when: false

    - name: Sort user packages
      ansible.utils.update_fact:
        updates:
          - path: "output_config.user[{{ user_idx_sort }}].packages"
            value: "{{ item.packages | sort }}"
      register: _updated_fact
      changed_when: false
      loop: "{{ output_config.user }}"
      loop_control:
        index_var: user_idx_sort

    - name: Update output_config for user
      ansible.builtin.set_fact:
        output_config: "{{ _updated_fact.results[0].output_config }}"
      changed_when: false

    - name: Final configuration
      ansible.builtin.debug:
        msg: "{{ output_config }}"

    - name: Store final config file information to be used by ../config_files
      delegate_to: localhost
      ansible.builtin.copy:
        dest: "{{ playbook_dir }}/../build/configfiles.json"
        content: "{{ output_config | to_nice_json(indent=4) }}"
      changed_when: false

# - name: Run output_config playbook
#   ansible.builtin.import_playbook: ../output_config/build.yaml
#   tags:
#     - output_config

  # - name: Run scriptfiles playbook
  #   ansible.builtin.import_playbook: ../scriptfiles/main.yaml
  #   tags:
  #     - scriptfiles

  # - name: Copy config files
  #   ansible.builtin.copy:
  #     src: "{{ configfiles_path }}/*"
  #     dest: "/home/{{ user.id }}/"
