.PHONY: preconfigure configure postconfigure configfiles

all: preconfigure configure postconfigure

preconfigure:
	@. ./preconfigure.sh

configure:
	@. ./configure.sh

postconfigure:
	@. ./postconfigure.sh
