---
- name: Install exa
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"
      - "default.yaml"

- name: Load aliases
  ansible.builtin.include_vars:
    file: aliases.yaml
    name: _exa_aliases

- name: Update aliases
  ansible.builtin.include_role:
    name: per_user_aliases
  vars:
    alias_list: "{{ _exa_aliases }}"
