---
- name: Install git
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"
      - "default.yaml"

- name: Configure git email
  become_user: "{{ userid }}"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git.user_email }}"
    state: present
  when: git.user_email | length > 0

- name: Configure git name
  become_user: "{{ userid }}"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git.user_name }}"
    state: present
  when: git.user_name | length > 0

- name: Configure git GPG Key
  become_user: "{{ userid }}"
  community.general.git_config:
    name: user.signingKey
    scope: global
    value: "{{ git.gpg_key }}"
    state: present
  when: git.gpg_key | default("", True) | length > 0
