---
- hosts: thebrain
  become: true
  become_user: "{{ username }}"
  vars_files:
    - ../vars/_playbook.yaml
    - ../vars/secrets.yaml

  pre_tasks:
    - name: Debug
      ansible.builtin.debug:
        msg:
          - "Computed stats"
          - "  Shell: {{ shell }}"
          - "  Distribution: {{ distribution }}"
          - "  OS Family: {{ os_family }}"
          - "  Development Environments: {{ dev_roles | join(', ') }}"
        verbosity: 1

  roles:
    - git
    - docker

  tasks:
    - name: Install zsh.
      when: machine.shell == 'zsh'
      include_role:
        name: zsh

    - name: Install oh-my-zsh.
      when: machine.shell == 'zsh' and machine.ohmyzsh.path | length > 0
      include_role:
        name: ohmyzsh
