# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../common/vars/global.yaml

  pre_tasks:
    - name: Import configuration
      ansible.builtin.set_fact:
        configfiles: "{{ lookup('file', playbook_dir + '/../build/configfiles.json') | from_json }}"

    - name: Display info
      ansible.builtin.debug:
        msg:
          - "Config files: {{ configfiles }}"
        verbosity: 1

  roles:
    - mnussbaum.base16-builder-ansible

  tasks:
    - name: Development
      ansible.builtin.debug:
        msg: Development Configuration

    - name: Go config
      ansible.builtin.include_tasks: tasks/development/go.yaml
      when: '"go" in configfiles.configs'

  #   - name: Node config
  #     when: '"node" in config_roles'
  #     ansible.builtin.include_tasks: tasks/development/node.yaml

  #   - name: Python config
  #     when: '"python" in config_roles'
  #     ansible.builtin.include_tasks: tasks/development/python.yaml

  #   - name: Rust config
  #     when: '"rust" in config_roles'
  #     ansible.builtin.include_tasks: tasks/development/rust.yaml

  #   - name: Zsh config
  #     when: '"zsh" in config_roles'
  #     ansible.builtin.include_tasks: tasks/shell/zsh.yaml

    - name: Generate scheme colors
      base16_builder:
        scheme: "{{ base16.color_scheme }}"
        template: "{{ base16.templates }}"
      register: base16_schemes

  #   # - debug:
  #   #     var: base16_schemes

    - name: Alacritty Config
      when: '"alacritty" in applications'
      ansible.builtin.include_tasks: tasks/application/alacritty.yaml

  #   - name: Copy files to output
  #     ansible.builtin.copy:
  #       src: files/*
  #       dest: output/
