---
- when: ansible_os_family != 'Redhat'
  ansible.builtin.set_fact:
    cloud_image_utils_packages:
      - cloud-utils

- when: ansible_os_family == 'Redhat'
  ansible.builtin.set_fact:
    cloud_image_utils_packages:
      - cloud-utils
      - cloud-utils-growpart

- name: Install cloud-image-utils
  when: ansible_os_family == 'Debian'
  ansible.builtin.package:
    name: "{{ cloud_image_utils_packages }}"
    state: present

- name: Get date
  ansible.builtin.command:
    cmd: date +"%Y-%m-%d"
  register: _date
  changed_when: false

- name: Create cloud-init image
  ansible.builtin.command:
    cmd: "cloud-localds -f iso9660 ./images/cloud-config-{{ config_name }}-{{ _date.stdout }}.img ./configs/{{ config_name }}-user.yaml  ./configs/{{ config_name }}-meta.yaml"
