---
- name: Install cloud-image-utils
  ansible.builtin.package:
    name: cloud-image-utils
    state: present

- name: Get date
  ansible.builtin.command:
    cmd: date +"%Y-%m-%d"
  register: _date
  changed_when: false

- name: Create cloud-init image
  ansible.builtin.command:
    cmd: "cloud-localds  -d qcow2 ./images/cloud-config-{{ config_name }}-{{ _date.stdout }}.qcow2 ./configs/{{ config_name }}.yaml"
