---
- when: ansible_os_family != 'Redhat'
  ansible.builtin.set_fact:
    cloud_image_utils_packages:
      - cloud-utils

- when: ansible_os_family == 'Redhat'
  ansible.builtin.set_fact:
    cloud_image_utils_packages:
      - cloud-utils
      - cloud-utils-growpart

- name: Install cloud-image-utils
  when: ansible_os_family == 'Debian'
  ansible.builtin.package:
    name: "{{ cloud_image_utils_packages }}"
    state: present

- name: Get date
  ansible.builtin.command:
    cmd: date +"%Y-%m-%d"
  register: _date
  changed_when: false

- name: Set config_name
  when: config_name != ""
  ansible.builtin.set_fact:
    _config_image_config_name_str: "{{ config_name }}-"

- name: Set config_name
  when: config_name == ""
  ansible.builtin.set_fact:
    _config_image_config_name_str: ""

- name: Create cloud-init nocloud data-source image
  ansible.builtin.command:
    cmd: "cloud-localds -f iso9660 {{ image_path }} {{ user_config_path }} {{ meta_config_path }}"
