# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook
---
- hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Set output directory
      ansible.builtin.set_fact:
        _configfiles_output_dir: "{{ playbook_dir ~ '/../build/service_files/' }}"
