---
galaxy_info:
  author: Simon Kennedy
  description: Install docker and python docker library
  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - docker

dependencies: []
