---
- hosts: all
  become: true
  become_user: "{{ username }}"
  vars_files:
    - ../vars/_playbook.yaml
    - ../vars/secrets.yaml

  pre_tasks:
    - name: Debug
      ansible.builtin.debug:
        msg:
          - "Computed stats"
          - "  Configuration file home directory: {{ config_home }}"
          - "  Shell: {{ shell }}"
          - "  Distribution: {{ distribution }}"
          - "  OS Family: {{ os_family }}"
          - "  Development Environments: {{ dev_roles | join(', ') }}"

  roles:
    - git
    - dev
  #   - role: xdg_user_dirs
  #     vars:
  #       custom_xdg_user_dirs:
  #         XDG_PUBLICSHARE_DIR:
    - docker

  tasks:
    - name: Install zsh.
      include_role:
        name: zsh
      when: shell == 'zsh'

    - name: Install oh-my-zsh.
      include_role:
        name: ohmyzsh
      when: shell == 'zsh' and zsh.ohmyzsh.path | length > 0

    - name: Install Go dev environment.
      include_role:
        name: development_go
      when: '"go" in development_roles'

    - name: Install Node dev environment.
      include_role:
        name: development_node
      when: '"node" in development_roles'

    - name: Install Python dev environment.
      include_role:
        name: development_python
      when: '"python" in development_roles'

    - name: Install Rust dev environment.
      include_role:
        name: development_rust
      when: '"rust" in development_roles'

  #   - name: Install config files
  #     ansible.builtin.git:
  #       repo: 'https://github.com/sffjunkie/configfiles'
  #       dest: "{{ config_home }}"
