---
picom_pre_requisites:
  package:
    - dbus-devel
    - gcc
    - libconfig-devel
    - libdrm-devel
    - libev-devel
    - libX11-devel
    - libX11-xcb
    - libXext-devel
    - libxcb-devel
    - mesa-libGL-devel
    - pcre-devel
    - pixman-devel
    - uthash-devel
    - xcb-util-image-devel
    - xcb-util-renderutil-devel
    - xorg-x11-proto-devel
