---
- name: Dev | Common Development Environment
  block:
    - name: Dev | Common | Load os/distribution specific package list
      ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - '{{ distribution }}.yaml'
            - '{{ os_family }}.yaml'
            - 'default.yaml'
          paths:
            - 'packages'

    - name: Dev | Common | Install packages
      when: dev_common_packages.keys() | length > 0
      ansible.builtin.include_role:
        name: install_group
      vars:
        group: "{{ dev_common_packages }}"
