---
- name: "Create development directories in /home/{{ userid }}"
  ansible.builtin.file:
    path: "/home/{{ userid }}/{{ item }}"
    state: directory
    mode: 0750
    access_time: preserve
    modification_time: preserve
    owner: "{{ userid }}"
    group: "{{ userid }}"
  loop: "{{ development.dirs }}"

- name: Install common packages
  ansible.builtin.include_role:
    name: install_packages
  vars:
    install: "{{ development.common }}"

- name: Install development environments.
  ansible.builtin.include_role:
    name: "development_{{ language }}"
  loop: "{{ development.roles }}"
  loop_control:
    loop_var: language
