---
- name: "Create development directories in /home/{{ userid }}"
  file:
    path: "/home/{{ userid }}/{{ item }}"
    state: directory
    mode: 0750
    access_time: preserve
    modification_time: preserve
    owner: "{{ userid }}"
    group: "{{ userid }}"
  loop: "{{ development_dirs }}"

- name: Install dev environment.
  include_role:
    name: "development_{{ language }}"
  loop: "{{ development_roles }}"
  loop_control:
    loop_var: language
