# This playbook needs to be run as the 'default_user'
---
- hosts: machines
  become: true
  vars_files:
    - ../common/vars/global.yaml
    - ./vars/secrets.yaml

  pre_tasks:
    - name: Convert default_user to something we can merge with system_users
      ansible.builtin.set_fact:
        _default_user: "{{ _default_user | default({}) | combine({ item.key: item.value }) }}"
      loop:
        - { key: "{{ default_user.id }}", value: "{{ default_user }}" }

    - name: Set default cli_users
      when: not users_file is defined
      ansible.builtin.set_fact:
        _cli_users: {}

    - name: Load user file
      when: users_file is defined and users_file | length > 0
      ansible.builtin.set_fact:
        _cli_users: "{{ lookup('file', users_file) | from_yaml }}"

    - name: Load user file
      ansible.builtin.set_fact:
        users: "{{ _default_user | combine(system_users, _cli_users) }}"

  roles:
    - hostname
    - ssh_server
    - user_system
    - etc_issue
