# This playbook needs to be run as the 'user_default'
---
- hosts: machines
  become: true
  become_user: "{{ user_default.id }}"
  vars_files:
    - ../common/vars/global.yaml

  pre_tasks:
    - name: Set default users_cli
      when: not users_file is defined
      ansible.builtin.set_fact:
        users_cli: []

    - name: Load user file
      when: users_file is defined and users_file | length > 0
      ansible.builtin.set_fact:
        users_cli: "{{ lookup('file', user_file }}"

    - name: Load user file
      ansible.builtin.set_fact:
        users: "{{ [user_default] + users_common + users_cli }}"

    - name: Show user list
      ansible.builtin.debug:
        msg:
          - Creating users
          - "{{ users }}"

  # roles:
  #   - hostname
  #   - ssh_server
  #   - role: user_system
  #     user_list: "{{ users }}"
