---
- name: Install packages
  ansible.builtin.package:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present

- name: Enable unattended-upgrades
  ansible.builtin.service:
    enabled: true
    state: started
    name: unattended-upgrades
