# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook
---
- hosts: unifi
  become: true
  vars_files:
    - ../common/vars/global.yaml

  roles:
    - playbook_packages
    - mongodb
    - unifi
