---
- hosts: thebrain
  become: true
  become_user: "{{ username }}"
  vars_files:
    - ../common/vars/main.yaml
    - ../vars/secrets.yaml

  pre_tasks:
    - name: Debug
      ansible.builtin.debug:
        msg:
          - "Computed stats"
          - "  Configuration file home directory: {{ config_home }}"
          - "  Shell: {{ shell }}"
          - "  Distribution: {{ distribution }}"
          - "  OS Family: {{ os_family }}"
          - "  Development Environments: {{ dev_roles | join(', ') }}"

  roles:
    - git
    - docker

  tasks:
    - name: Install zsh.
      when: machine.shell == 'zsh'
      include_role:
        name: zsh

    - name: Install oh-my-zsh.
      when: machine.shell == 'zsh' and machine.ohmyzsh.path | length > 0
      include_role:
        name: ohmyzsh

  #   - name: Install config files
  #     ansible.builtin.git:
  #       repo: 'https://github.com/sffjunkie/configfiles'
  #       dest: "{{ config_home }}"
