---
- name: Install Oh-My-ZSH.
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  environment:
    ZSH: "{{ zsh.ohmyzsh.path }}"

- name: Install plugins.
  git:
    repo: "https://github.com/zsh-users/{{ item }}.git"
  loop:
    "{{ zsh.ohmyzsh.plugins }}"
