---
- name: Load default package_list
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{distribution}}.yaml'
        - '{{os_family}}.yaml'
      paths:
        - 'vars'

- name: Add to package_list.
  set_fact:
    package_list: "{{ (os_packages + custom_os_packages) | unique }}"

- name: Install package
  package:
    name: "{{ item }}"
    state: present
  loop:
    "{{ package_list | default([], True) }}"
  when: package_list | default([], True) | length > 0
