---
- name: Get base16-shell path
  ansible.builtin.set_fact:
    base16_shell_path: "{{ local_home }}/base16-shell"

- name: Install base 16 shell
  ansible.builtin.git:
    repo: https://github.com/chriskempson/base16-shell.git
    dest: "{{ base16_shell_path }}"
    version: HEAD  # noqa: git-latest

- name: Install base16-shell-preview
  ansible.builtin.pip:
    name: base16-shell-preview
    extra_args: --user

- name: Update configfiles fact
  ansible.builtin.set_fact:
    configfiles: "{{ configfiles + [['base16', { 'path': base16_shell_path }]] }}"
