---
- name: Load default os package list
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{distribution}}.yaml"
        - "{{os_family}}.yaml"
      paths:
        - "vars"

- name: Install base packages
  ansible.builtin.package:
    name: "{{ base_os_packages }}"
    state: present
  # loop: "{{ base_os_packages }}"
