---
- name: Development Environments | Ansible
  ansible.builtin.debug:
    msg: Building Ansible Development Environment
    verbosity: 1

- name: Development Environments | Ansible | Load os/distribution specific package list
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ distribution }}.yaml'
        - '{{ os_family }}.yaml'
        - 'all.yaml'
      paths:
        - 'packages'

- name: Development Environments | Ansible | Install packages
  ansible.builtin.include_role:
    name: install_group
  vars:
    group: "{{ dev_ansible_packages }}"

- name: Development Environments | Ansible | Clone ansible git repository
  ansible.builtin.git:
    repo: https://github.com/ansible/ansible.git
    dest: "/home/{{ user_id }}/development/source/ansible"
    version: HEAD  # noqa: git-latest

- name: Development Environments | Ansible | Update output_config
  block:
    - name: Development Environments | Ansible | Calc new output_config
      ansible.utils.update_fact:
        updates:
          - path: "output_config.user[{{ user_idx }}].packages"
            value: "{{ output_config.user[user_idx].packages + ['ansible'] }}"
      register: _updated_fact
      changed_when: false

    - name: Development Environments | Ansible | Update output_config
      ansible.builtin.set_fact:
        output_config: "{{ _updated_fact.output_config }}"
      changed_when: false
