---
- name: Calc CARGO_HOME
  ansible.builtin.set_fact:
    _cargo_home: "{{ local_home }}/cargo"

- name: Calc cargo bin directory
  ansible.builtin.set_fact:
    _cargo_bin: "{{ _cargo_home }}/bin"

- name: Calc RUSTUP_HOME
  ansible.builtin.set_fact:
    _rustup_home: "{{ local_home }}/rust"

- name: Update configfiles for rust
  block:
    - ansible.builtin.set_fact:
        _rust_config:
          rust:
            CARGO_HOME: "{{ _cargo_home }}"
            RUSTUP_HOME: "{{ _rustup_home }}"

    - ansible.utils.update_fact:
        updates:
          - path: configfiles.path
            value: "{{ configfiles.path + [_cargo_bin] }}"
          - path: configfiles.configs
            value: "{{ configfiles.configs | combine(_rust_config) }}"
      register: _updated_fact
      changed_when: false

    - ansible.builtin.set_fact:
        configfiles: "{{ _updated_fact.configfiles }}"
      changed_when: false
