---
- name: "Rust: Calculate CARGO_HOME"
  ansible.builtin.set_fact:
    _cargo_home: "{{ local_home }}/cargo"

- name: "Rust: Calculate cargo bin directory"
  ansible.builtin.set_fact:
    _cargo_bin: "{{ _cargo_home }}/bin"

- name: "Rust: Calculate RUSTUP_HOME"
  ansible.builtin.set_fact:
    _rustup_home: "{{ local_home }}/rust"

- name: "Rust: Update configfiles"
  block:
    - ansible.builtin.set_fact:
        _rust_config:
          rust:
            CARGO_HOME: "{{ _cargo_home | replace(home, '${HOME}') }}"
            RUSTUP_HOME: "{{ _rustup_home | replace(home, '${HOME}') }}"

    - ansible.utils.update_fact:
        updates:
          - path: configfiles.pathend
            value: "{{ configfiles.pathend + [_cargo_bin | replace(home, '${HOME}')] }}"
          - path: configfiles.configs
            value: "{{ configfiles.configs | combine(_rust_config) }}"
      register: _updated_fact
      changed_when: false

    - ansible.builtin.set_fact:
        configfiles: "{{ _updated_fact.configfiles }}"
      changed_when: false
