---
- name: Install pyenv
  shell: "curl https://pyenv.run | bash"  # noqa command-instead-of-module
  environment:
    PYENV_ROOT: "{{ local_home }}"
  args:
    creates: "{{ local_home }}/.pyenv"
  pipefail: true

- name: Set configfiles property
  ansible.builtin.set_fact:
    config_files: "{{ config_files + [{ 'pyenv_path': local_home + '/pyenv/bin' }] }}"
