---
- name: Development Environments | Typescript
  ansible.builtin.debug:
    msg: Building Typescript Development Environment
    verbosity: 1

- name: Development Environments | Typescript | Load os/distribution specific package list
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ distribution }}.yaml'
        - '{{ os_family }}.yaml'
        - 'all.yaml'
      paths:
        - 'packages'

- name: "Development Environments | Typescript | Install"
  ansible.builtin.include_role:
    name: install_group
  vars:
    group: "{{ dev_typescript_packages }}"

- name: Development Environments | Typescript | Update output_config
  block:
    - name: Typescript | Calc config
      ansible.builtin.set_fact:
        _ts_config:
          typescript: {}

# TODO: dev_typescript | pathend, configs, envvar
    - name: Development Environments | Typescript | Calc new output_config
      ansible.utils.update_fact:
        updates:
#           - path: output_config.pathend
#             value: "{{ output_config.pathend + [_npm_bin_path] }}"
#           - path: output_config.configs
#             value: "{{ output_config.configs }}"
#           - path: output_config.envvar
#             value: >
#               "{{ output_config.envvar |
#               combine({'NPM_PACKAGES': _npm_install_path + '/go'}) }}"
          - path: output_config.packages
            value: "{{ output_config.packages + ['typescript'] }}"
      register: _updated_fact
      changed_when: false

    - name: Development Environments | Typescript | Update output_config
      ansible.builtin.set_fact:
        output_config: "{{ _updated_fact.output_config }}"
      changed_when: false
