---
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "nodejs"
    - "npm"

- name: Install global packages
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop:
    - "typescript"
    - "@types/node"
    - "@micrsoft/tsdoc"
    - "typedoc"
