---
- hosts: ubuntu
  become: true

  vars:
    ssh_port: 22

  vars_files:
    - files/secrets.yaml

  tasks:
    - name: Configure ssh server.
      import_role:
        name: ssh
        vars:
          ssh_port: {{ ssh_port }}

    - name: Add user.
      import_role:
        name: user_add
      loop: {{ usernames }}
      loop_control: "userid"

    - name: Configure ssh for user.
      import_role:
        name: user_ssh
      loop: {{ usernames }}
      loop_control: "userid"

    - import_role:
        name: ufw
        vars:
          ssh_port: {{ ssh_port }}

    - name: Install Python SELinux library.
      package:
        name: python3-libselinux
        state: present

    - name: Ensure SELinux is enabled in `targeted` mode.
      selinux:
        policy: targeted
        state: enforcing

    - name: Ensure httpd can connect to the network.
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
      when: ansible_selinux.status == 'enabled'
