---
- name: Create temporary directory
  ansible.builtin.tempfile:
    prefix: compose
    state: directory
  register: _compose_tmp_dir
  notify:
    - Delete temporary files
  changed_when: false

- name: Check if docker-compose exists
  ansible.builtin.stat:
    path: "/usr/local/bin/"
  register: _compose_exists

- name: Download compose binary
  when: not _compose_exists.stat.exists
  ansible.builtin.uri:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: "{{ _compose_tmp_dir.path }}/docker-compose"
    mode: "+x"
  changed_when: false

- name: Copy compose file
  when: not _compose_exists.stat.exists
  ansible.builtin.copy:
    src: "{{ _compose_tmp_dir.path }}/docker-compose"
    dest: "/usr/local/bin/"
    remote_src: true
