---
- name: Development Environments | Rust
  ansible.builtin.debug:
    msg: Building Rust Development Environment
    verbosity: 1

- name: Development Environments | Rust | Set pyenv_root fact
  ansible.builtin.set_fact:
    cargo_home: "/home/{{ user_id }}/.local/cargo"
    cargo_home_text: "{{ local_home_text }}/cargo"

- name: Development Environments | Rust | Calculate cargo bin directory
  ansible.builtin.set_fact:
    cargo_bin: "{{ cargo_home }}/bin"
    cargo_bin_text: "{{ cargo_home_text }}/bin"

- name: Development Environments | Rust | Calculate RUSTUP_HOME
  ansible.builtin.set_fact:
    rustup_home: "/home/{{ user_id }}/.local/rust"
    rustup_home_text: "{{ local_home_text }}/rust"

- name: Development Environments | Rust | Create temporary directory
  ansible.builtin.tempfile:
    prefix: rust
    state: directory
  changed_when: false
  register: _rust_tmp
  notify: Delete temporary rust directory

- name: Development Environments | Rust | Set tmp directory owner to user_id
  ansible.builtin.file:
    path: "{{ _rust_tmp.path }}"
    owner: "{{ user_id }}"
    group: "{{ user_id }}"
    mode: 0755
  changed_when: false

- name: Development Environments | Rust | Download install script
  become_user: "{{ user_id }}"
  ansible.builtin.uri:
    url: https://sh.rustup.rs
    dest: "{{ _rust_tmp.path }}/rustup.sh"
    mode: 0755
  changed_when: false

- name: Development Environments | Rust | Run install script
  become_user: "{{ user_id }}"
  ansible.builtin.command:
    cmd: >-
      bash -c '{{ _rust_tmp.path }}/rustup.sh -y --no-modify-path
      --default-toolchain {{ env_config.toolchain }}'
    creates: "{{ cargo_home }}/env"
  environment:
    CARGO_HOME: "{{ cargo_home }}"
    RUSTUP_HOME: "{{ rustup_home }}"

- name: Development Environments | Rust | Delete temporary directory
  ansible.builtin.file:
    path: "{{ _rust_tmp.path }}"
    state: absent
  changed_when: false

- name: Development Environments | Rust | Update output_config
  block:
    - name: Development Environments | Rust | Calc config
      ansible.builtin.set_fact:
        _rust_config:
          rust:
            CARGO_HOME: "{{ cargo_home_text }}"
            RUSTUP_HOME: "{{ rustup_home_text }}"

    - name: Development Environments | Rust | Calc new output_config
      ansible.utils.update_fact:
        updates:
          - path: "output_config.user[{{ user_idx }}].pathend"
            value: "{{ output_config.user[user_idx].pathend + [cargo_bin_text] }}"

          - path: "output_config.user[{{ user_idx }}].configs"
            value: "{{ output_config.user[user_idx].configs | combine(_rust_config) }}"

          - path: "output_config.user[{{ user_idx }}].packages"
            value: "{{ output_config.user[user_idx].packages + ['rust'] }}"
      register: _updated_fact
      changed_when: false

    - name: Development Environments | Rust | Update output_config
      ansible.builtin.set_fact:
        output_config: "{{ _updated_fact.output_config }}"
      changed_when: false
