---
- name: Rust Dev
  ansible.builtin.debug:
    msg: Building Rust Development Environment
    verbosity: 1

- name: "Rust | Calculate CARGO_HOME"
  ansible.builtin.set_fact:
    _cargo_home: "$_LOCAL_HOME/cargo"

- name: "Rust | Calculate cargo bin directory"
  ansible.builtin.set_fact:
    _cargo_bin: "{{ _cargo_home }}/bin"

- name: "Rust | Calculate RUSTUP_HOME"
  ansible.builtin.set_fact:
    _rustup_home: "$_LOCAL_HOME/rust"

- name: Rust | Create temporary directory
  ansible.builtin.tempfile:
    prefix: rust
    state: directory
  changed_when: false
  register: _rust_tmp
  notify: Delete temporary rust directory

- name: Rust | Set tmp directory owner to userid
  ansible.builtin.file:
    path: "{{ _rust_tmp.path }}"
    mode: 0755
    owner: "{{ userid }}"
    group: "{{ userid }}"
  changed_when: false

- name: Rust | Download install script
  become_user: "{{ userid }}"
  ansible.builtin.uri:
    url: https://sh.rustup.rs
    dest: "{{ _rust_tmp.path }}/rustup.sh"
  changed_when: false

- name: Rust | Set install script permissions
  ansible.builtin.file:
    path: "{{ _rust_tmp.path }}/rustup.sh"
    mode: 0755
  changed_when: false

- name: Rust | Run install script
  become_user: "{{ userid }}"
  ansible.builtin.command:
    cmd: >
      "bash -c '{{ _rust_tmp.path }}/rustup.sh -y --no-modify-path
      --default-toolchain {{ machine.development.rust.toolchain }}'"
    creates: "$_LOCAL_HOME/cargo/env"
  register: _rust_install
  environment:
    CARGO_HOME: "{{ _cargo_home }}"
    RUSTUP_HOME: "{{ _rustup_home }}"

- name: Rust | Delete temporary directory
  ansible.builtin.file:
    path: "{{ _rust_tmp.path }}"
    state: absent
  changed_when: false

- name: Rust | Update configfiles
  block:
    - name: Rust | Calc config
      ansible.builtin.set_fact:
        _rust_config:
          rust:
            CARGO_HOME: "{{ _cargo_home | replace(home, '${HOME}') }}"
            RUSTUP_HOME: "{{ _rustup_home | replace(home, '${HOME}') }}"

    - name: Rust | Calc new configfiles fact
      ansible.utils.update_fact:
        updates:
          - path: configfiles.pathend
            value: "{{ configfiles.pathend + [_cargo_bin | replace(home, '${HOME}')] }}"
          - path: configfiles.configs
            value: "{{ configfiles.configs | combine(_rust_config) }}"
          - path: configfiles.packages
            value: "{{ configfiles.packages + ['rust'] }}"
      register: _updated_fact
      changed_when: false

    - name: Rust | Update configfiles fact
      ansible.builtin.set_fact:
        configfiles: "{{ _updated_fact.configfiles }}"
      changed_when: false
