---
- name: Create and set permissions for .ssh directory
  ansible.builtin.file:
    path: "/home/{{ user.id }}/.ssh"
    mode: 0700
    state: directory
    owner: "{{ user.id }}"
    group: "{{ user.id }}"
    access_time: preserve
    modification_time: preserve

- name: create authorized_keys file
  ansible.builtin.file:
    path: "/home/{{ user.id }}/.ssh/authorized_keys"
    state: touch
    mode: 0644
    owner: "{{ user.id }}"
    group: "{{ user.id }}"
    access_time: preserve
    modification_time: preserve

- name: Add id to authorized_keys
  become_user: "{{ user.id }}"
  vars:
    pub_content: "{{ lookup('file', '/home/{{ user.id }}/.ssh/{{ user.public_key_file }}') }}"
  ansible.builtin.lineinfile:
    dest: /home/{{ user.id }}/.ssh/authorized_keys
    regexp: "^{{ pub_content }}"
    line: "{{ pub_content }}"
    state: present
