---
- name: Install flatpak
  when: os_family == 'debian'
  ansible.builtin.package:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
    state: present

- name: Install flatpak
  when: os_family == 'archlinux'
  community.general.pacman:
    name: flatpak
    state: present

- name: Add flatpak repository
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
