---
- name: Enabled Development Environments.
  when: language.value.enabled | default(true) == true
  ansible.builtin.debug:
    msg: "{{ language.key }} enabled"
  loop: "{{ lookup('dict', machine.development.roles) }}"
  loop_control:
    loop_var: language

- name: Install Development Environments.
  when: language.value.enabled | default(true) == true
  ansible.builtin.include_role:
    name: "dev_{{ language.key }}"
  vars:
    env_info: "{{ language.value }}"
  loop: "{{ lookup('dict', machine.development.roles) }}"
  loop_control:
    loop_var: language
