---
# vars -
#   for_pulseaudio: false
#   for_alsa: false
#   for_jack: false

- name: Pipewire | OS Install
  ansible.builtin.include_tasks: "{{ lookup('first_found', subtasks) }}"
  vars:
    subtasks:
      - "{{ distribution }}.yaml"
      - "{{ os_family }}.yaml"
      - "default.yaml"
